apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam-deployment-for-asg
  labels:
    app: imdeployementapp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: all-app-under-me
  template: 
    metadata:
      name: i-am-a-container
      labels:
        app: all-app-under-me
    spec:
      containers:
        - name: cpu-demo
          image: k8s.gcr.io/hpa-example
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          ports:
            - containerPort: 80




---

apiVersion: v1
kind: Service
metadata:
  name: i-am-service
spec:
  selector:
    app: all-app-under-me
  ports:
    - port: 80
      targetPort: 80
      